webextensions/_locales/zh_CN/messages.json
The older XPCOM addon supported Chinese locale, but we did
not ported the support to new Web Extension. This patch is
an attempt to fix that.
Note: These messages are translated from the Japanese locale
(and sometimes, English locale) using DeepL Pro License.
Signed-off-by: Fujimoto Seiji <fujimoto@clear-code.com>
=> Add the first cut at Chinese support

webextensions/_locales/zh_CN/messages.json
We needed this in order to avoid showing "_MSG__countdown..." in
the dialog. Fix it.
Signed-off-by: Fujimoto Seiji <fujimoto@ceptord.net>
=> Add a empty character as a filler

.github/workflows/build-release.yaml, webextensions/native-messaging-host/build.sh
We need to set up build environment, respectively.
For every commit, we can build binary via GitHub actions.
It make easy to prepare pre-built binary without development environment.
=> github: add build action for FlexConfirmMail

.github/workflows/build-release.yaml
Related to #19, but not remove XUL version yet.
In the previous PR, it build deprecated XUL version of xpi too.
In this PR, it build only webextension version of xpi.
Run GitHub actions and see built assets.
No flex-confirm-mail.xpi in assets.
=> github: do not pack xul version of xpi

webextensions/common/matching-rules.js, webextensions/manifest.json
N/A
There is a confusing behavior around multiple level configs from GPO of Outlook, GPO of Thunderbird, and policies.json. This PR stabilize it based on the order of config sources described at here: https://github.com/piroor/webextensions-lib-configs/blob/f950a9a43694cce90ed922318d1da3fe753ae153/Configs.js#L10-L23
* Install FlexConfirmMail to Thunderbird and configure it. 
* Configure GPO of FlexConfirmMail for Outlook.
* Configure FlexConfirmMail with policies.json.
* Start Thunderbird and confirm that configs are applied with the order described at https://github.com/piroor/webextensions-lib-configs/blob/f950a9a43694cce90ed922318d1da3fe753ae153/Configs.js#L10-L23
1. Prepare the environment.
1. Prepare a Windows environment, e.g. Windows 10 22H2.
2. Download policy template of …
=> Apply unlocked managed value as default value

webextensions/common/common.js
N/A
Fix  a typo in sending a message to host.
```
loggging ->
logging
```
N/A
It is not used effectively from webextension.
N/A
=> Fix a typo in sendToHost

webextensions/native-messaging-host/build_pkg.sh
N/A
If we just notarize the pkg, the Mac machine needs to be online before using notarized pkg. Stapling allows us to run the pkg without online validation.
Try to install stapled pkg without any error even if the Mac machine is offline.
1. Prepare a signed, notarized and stapled pkg.
2. Copy the file to another Mac machine.
3. Make the machine offline.
4. Install the pkg.
The pkg should be installed successfully.
=> Staple notarization status to the signed package for offline install

webextensions/manifest.json, webextensions/native-messaging-host/host.go
N/A
Increments the version to 4.1.6 for a new release.
Install the built package and check its display version.
1. Run `make`.
2. Install xpi to Thunderbird.
3. Enter webextensions/native-messaging-host and run `build_msi.bat` to build MSI.
4. Run the built MSI to install the native messaging host.
5. Go to the list of installed applications on Windows.
* Verify the installed version is `4.1.6`.
6. Drag the built XPI and drop onto Thudnerbird's addons manager.
* Verify the installed version is `4.1.6`.
The installed version is displayed as `4.1.6`.
=> Bump version to 4.1.6

webextensions/common/matching-rules.js
N/A
`test_classifyAttachments` fails due to some changes introduced at old versions. This fixes the implementation to pass the existing test.
Run the automated test.
1. Clone this repository.
2. cd `webextensions`.
3. run `npm install`.
4. run `npm run test`. 
All tests should pass.
=> Detect files with specified extensions correctly

webextensions/_locales/en/messages.json, webextensions/_locales/ja/messages.json, webextensions/common/matching-rules.js, webextensions/common/recipient-classifier.js, webextensions/options/init.js, webextensions/options/options.html, webextensions/test/test-matching-rules.js, webextensions/test/test-recipient-classifier.js
N/A
This change will make FlexConfirmMail supporting wildcards in domains and terms.
Try to use domains and terms with wildcards.
1. Build the XPI.
2. Install XPI to your Thunderbird.
3. Setup FlexConfirmMail as:
* internal domains: `*.example.com`
* specially confirmed external domains: `*.example.org`
* specially confirmed terms for attachments: `set*up`
4. Prepare a text file with filename `set-up.txt`
5. Start composition
6. Set recipients: `example@internal.example.com`, `example@group.example.com`, `example@dangerous.example.org` and `example@fake.example.org`
7. Attach the file `set-up.txt`
8. Try to send the message
* All `*.example.com` recipients should be detected as internal domains
* All `*.example.org` recipients should be detected as specially confirmed domains
* The …
=> Wildcard support

webextensions/manifest.json, webextensions/native-messaging-host/host.go
N/A
This just bumps the version number to 4.1.7 from 4.1.6.
Build it and confirm versions are incremented.
1. Cd to `webextensions`.
2. Run `make` to build XPI.
3. Run `make host` to build the native messaging host.
4. Install XPI to Thunderbird and confirm its version.
5. Start `cmd.exe` on Windows and run `webextensions/native-messaging-host/amd64/host.exe` (on Windows 64bit) with an option `-v` to confirm the reported version.
Both versions are 4.1.7.
=> Bump version to 4.1.7

webextensions/background/background.js, webextensions/common/common.js, webextensions/dialog/countdown/countdown.js
N/A
Sometimes the countdown feature fails to close the dialog it self and shows negative counts.
This change adds codes to output more logs around the feature and introduces failsafe on such case.
Try sending mail with countdown.
1. Install.
2. Configure to show countdown and activate the debug mode.
3. Open debugger console for this addon.
4. Try to send a message.
* Detailed logs are reported in the debugger console.
* Message is sent when the count become zero as expected.
=> Output more debuggable log around countdown feature

webextensions/_locales/en/messages.json, webextensions/_locales/ja/messages.json, webextensions/background/background.js, webextensions/common/common.js, webextensions/dialog/confirm/confirm.js, webextensions/manifest.json, webextensions/options/options.html
N/A
Miss selection from auto-completed recipients can happen when a user tries to reply an existing message and adds new recipients manually.
It sometimes causes fatal mistake like "I hope to add another member to this conversation exclusive with companies A and B, but unexpectedly added a different recipient of a third company C who has an email address local part same to another member of A or B.
This PR introduces new confirmation option for such cases: when a composition is started as a reply to an existing message, this memorizes all domains of existing recipients. After composition and on sending, this compares domains of final recipients and shows extra confirmation if there is any new recipients with a domain different from memorized known domains. (Moreover, recipients matching …
=> Alert for added new domain

webextensions/background/background.js, webextensions/common/recipient-classifier.js, webextensions/test/test-recipient-classifier.js
N/A
Currently this addon supports only matching with the domain part of recipients.
This PR adds support to define patterns containing local part.
You need to write patterns with local part with the special delimiter `@`, in other words, patterns without `@` are treated as just domain patterns for backward compatibility.
Try to define patterns with local part and verify that matched recipients are detected as expected.
1. Assume that you have a GMail account and `gmail.com` is not an internal domain.
2. Add a pattern with local part matching to your address to the list of internal domains. For example, if your address is `piro.outsider.reflex@gmail.com`, you should add `piro*@gmail.com`.
3. Compose a new message to multiple recipients including both internal and external domains.
4. Add …
=> Support matching to local part of recipients

webextensions/_locales/en/messages.json, webextensions/_locales/ja/messages.json, webextensions/_locales/zh_CN/messages.json, webextensions/common/common.js, webextensions/dialog/confirm/confirm.js, webextensions/dialog/countdown/countdown.js, webextensions/manifest.json
N/A
The message of reconfirmation dialogs are currently very flat and it is not clear what we should check about.
With this change, embedded addresses, domains, and other important part is emphasized more, and we can apply more custom style rules to emphasize arbitrary dialog.
Configure this addon to reconfirm some cases and see the actual dialog.
1. Install this addon.
2. Go to the options page of this addon, and set options:
* Recipients => Confirm when any recipients with domains different from any existing recipients are added (checked)
* Development => All Configs => extraStyleRules: set as `.rich-confirm-dialog.for-new-domain-recipients { background: red !important; padding: 1.5em; }  .rich-confirm-dialog.for-new-domain-recipients::before { color: white !important; content: …
=> Emphasize extra confirmation dialog contents more

webextensions/_locales/en/messages.json, webextensions/_locales/ja/messages.json
N/A
This updates  UI labels matching to changes introduced by the PR #43
Install XPI from the branch and see UI labels.
1. Install XPI.
2. Go to the options page of FlexConfirmMail.
Natural descriptions around internals.
=> Update UI text to match to actual behavior

webextensions/_locales/en/messages.json, webextensions/_locales/ja/messages.json, webextensions/common/matching-rules.js, webextensions/common/recipient-classifier.js, webextensions/test/test-matching-rules.js
N/A
This is a followup of #43. It adds address support for internal recipient patterns but extra rules are not supported. This adds address support for extra rules also.
Define and activate an extra rule with local part and try confirmation.
1. Define/activate an extra rule as:
* Matching target: recipient address
* Use a manually managed list
* Input `*+danger@example.com`
* Highlight on matched: Always
* When the condition matched: Re-confirm always
3. Composite a message with recipients `mail@example.com` and `mail+danger@example.com`, and try to send it.
* `mail+danger@example.com` is highlighted in the confirmation dialog.
* `mail+danger@example.com` is reconfirmed when you click "Send" in the confirmation dialog.
=> Matching to local part on extra rules

webextensions/manifest.json, webextensions/native-messaging-host/host.go
N/A
This increments the minor version.
Build XPI, install it, and confirm the version became 4.2.2.
1. Run `cd webextensions && make`.
2. Install the built XPI to Thunderbird via the Add-ons Manager.
3. See details of the installed FlexConfirmMail.
* The version number is 4.2.2.
=> Bump version to 4.2.2

webextensions/manifest.json
N/A
The countdown dialog sometimes fails to close itself when the system is overload.
This is caused by a bug of Thunderbird itself: a promise returned by browser.windows.create() is never resolved when the system is overload.
This PR updates revisions of depending libraries containing a fix for the problem.
Detailed changes of updated libraries:
https://gitlab.com/clear-code/webextensions-lib-dialog/-/commit/de5e942abe7fdfcbe368b1cf533ec32b3bd7bfe0
The main fix for this PR: handle new window without returned promise on such situations.
https://github.com/piroor/webextensions-lib-configs/compare/2ac38cbcfa43e09a9d8ec7664b5950463cbb27d0...9c9c0806a34499103f83de4519ca6bc79c733e24#diff-d05722551a04f7e474d6fe87aefc6ef9fd7eab2eec6013cb30634366bd431167
Supports both Manifest V2 and V3, and …
=> Update external libraries

webextensions/options/init.js
N/A
"Move Up", "Move Down" and "Remove" buttons of extra rules are not translated unexpectedly.
This applies localized messages for these buttons as their tooltip text.
Go to the options page and point those buttons.
1. Start Thunderbird.
2. Install this addon.
3. Open addons manager.
4. Click "Options" button for this addon.
5. Scroll the options page down and point right-top-edge buttons of an extra rule.
The tooltip text is localized.
> Describe the obvious situation to verify.
=> Localize tooltip of buttons

webextensions/native-messaging-host/host.go
N/A
This just increments the version number embedded in the native messaging host.
1. Build the native messaging host.
2. Run the built binary with "-v" option.
It reports 4.2.3.
=> Bump version embedded in the native messaging host

webextensions/manifest.json
Because the argument of accounts.list() was introduced at Tb 91.
N/A
This fixes the mismatched information mentioned at #56
1. Build XPI.
2. Start Thunderbird 78.
3. Try to install the built XPI.
4. Start Thunderbird 91.
5. Try to install the built XPI.
Thunderbird 78 rejects the XPI as unsupported.
Thunderbird 91 accepts the XPI.
=> Bump minVersion to 91.

.github/workflows/build-release.yaml
N/A
It is announced that the actions/upload-artifact@v3 will be closing down by 2025-01-30. We need to migrate to v4.
https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes
https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md
1. Run the workflow.
The result should have built binaries as artifacts.
=> Bump version of actions/upload-artifact

.github/workflows/build-release.yaml, webextensions/Makefile, webextensions/native-messaging-host/Makefile, webextensions/native-messaging-host/go.mod, webextensions/native-messaging-host/go.sum, webextensions/native-messaging-host/host.go, webextensions/native-messaging-host/host_darwin.go, webextensions/native-messaging-host/host_other.go, webextensions/native-messaging-host/host_test.go, webextensions/native-messaging-host/host_windows.go
N/A
This PR makes the implementation of the native messaging host more testable and adds automated tests for it.
1. Clone this repository.
2. Run `cd webextensions/native-messaging-host`
3. Run `go mod tidy`
4. Run `go test -v`
All tests pass.
=> Automated test for native messaging host

webextensions/_locales/zh_CN/messages.json
N/A
This PR aims to add Chinese language resources for untranslated messages.
1. Install Thunderbird with Chinese locale (zh-CN).
2. Start Thunderbird.
3. Install XPI.
4. Go to addons manager and open options page of the FlexConfirmMail.
All checkboxes are localized.
=> Add translations of newly added options

webextensions/_locales/en/messages.json
N/A
This fixes mismatched placeholder name of a locale definition. It should fix a problem of a confirmation dialog: the embedded recipients are missing.
1. Configure FlexConfirmMail to show confirmation for newly added recipient domains.
2. Run Thunderbird with English locale.
3. Prepare an existing message.
4. Start to compose a reply for the message.
5. Add a new recipient `mail@example.org` or something which has a new domain different from any existing recipients of the message, as a Bcc (or To/Cc).
6. Try to send the message and see the confirmation dialog.
7. Check all and continue.
An extra confirmation dialog should appear with a message like:
```
There are recipients with domains not included in the recipients of the original message.
(recipient addresses successfully embedded) …
```
=> Fix mismatched placeholder name

webextensions/background/background.js, webextensions/common/recipient-parser.js, webextensions/manifest.json, webextensions/test/test-recipient-parser.js
N/A
When a draft "下書き" message contains any mailing list (like "my-company <my-company>", it is populated to real email addresses when the message is really sent) as its recipients, FlexConfirmMail fails to populate them and cannot send the message. This change solves the limitation.
1. Hit Ctrl-Shift-B to open the address book.
2. Prepare multiple contacts in an address book.
3. Highlight multiple contacts with Shift/Ctrl-click.
4. Click the "New Address List" button in the rightmost pane.
5. Fill "Name" and "Nickname" fields.
6. Click "OK" button to save the list.
7. Start to composite a message.
8. Hit F9 o show the address sidebar.
9. Double-click a list (ex. the one created at the step 4).
10. The name of the list appears in the "To" field.
11. Save the message as a draft.
12. Close …
=> Populate list for draft

webextensions/manifest.json, webextensions/native-messaging-host/host.go
N/A
This just bumps the version number for the next release.
1. Build the XPI and the native messaging host.
2. See their version.
It is 4.2.5.
=> Bump version to 4.2.5

webextensions/_locales/zh_CN/messages.json
N/A
I unexpectedly re-introduced the already fixed bug #62 to a newly translated entry. This applies same change to the zh_CN locale.
1. Configure FlexConfirmMail to show confirmation for newly added recipient domains.
2. Run Thunderbird with Chinese (zh-CN) locale.
3. Prepare an existing message.
4. Start to compose a reply for the message.
5. Add a new recipient `mail@example.org` or something which has a new domain different from any existing recipients of the message, as a Bcc (or To/Cc).
6. Try to send the message and see the confirmation dialog.
7. Check all and continue.
An extra confirmation dialog should appear with a message like:
```
收件人添加了以下原邮件收件人中未包含的域名地址。
(recipient addresses successfully embedded)
请确认是否要发送此邮件？
```
=> Fix mismatched placeholder in zh_CN locale

Makefile, README.md, webextensions/Makefile, webextensions/_locales/en/messages.json, webextensions/_locales/ja/messages.json, webextensions/_locales/zh_CN/messages.json, webextensions/native-messaging-host/wix.json
N/A
This PR changes the display name of the addon to "FlexConfirmMail Stable", and updates URLs of the public webpage.
Some resources including the Native Messaging Host still don't have "stable" suffix - we'll rename them if needed in the future.
1. Build the XPI.
2. Install it to Thunderbird.
The display name has the suffix "Stable".
The built XPI also have the suffix.
=> Rename to FlexConfirmMail Stable

README.md, webextensions/managed-storage-examples/policies.json, webextensions/manifest.json, webextensions/native-messaging-host/com.clear_code.flexible_confirm_mail_we_host.macos.json, webextensions/native-messaging-host/com.clear_code.flexible_confirm_mail_we_host.windows.json
N/A
We are planning to separate update channels of this addon as:
* Regular channel: Based on the master branch. Any destructive changes may be merged. Published as https://addons.thunderbird.net/thunderbird/addon/flex-confirm-mail/ or https://addons.thunderbird.net/thunderbird/addon/flex-confirm-mail-progressive/
* Stable channel: Based on the stable branch from 4.2.5. Only screened and verified changes will be merged. Published as https://addons.thunderbird.net/thunderbird/addon/flex-confirm-mail-stable/
This PR changes the internal ID for the regular channel.
1. Build the XPI.
2. Install it to Thunderbird.
The display name has no suffix.
The built XPI have no suffix.
The internal ID is detected as `flexible-confirm-mail-progressive@clear-code.com` at about:debugging or about:support …
=> Reassign internal ID for non-stable releases
